version: 0.0
os: linux
files:
  - source: ./hello-sample-0.0.1-SNAPSHOT.jar
    destination: /tmp
  - source: ./script/starrt.sh
    destination: /tmp
hooks:
  ApplicationStart:
    - location: start.sh
