version: 0.0
os: linux
files:
  - source: ./hello-sample-0.0.1-SNAPSHOT.jar
    destination: /tmp
hooks:
  ApplicationStop:
    - location: sudo kill $(ps -ef | grep 'hello-sample-0.0.1-SNAPSHOT.jar' | grep -v 'grep' | awk '{ printf $2 }')
sudo kill $app_id
  ApplicationStart:
    - location: java -jar /tmp/hello-sample-0.0.1-SNAPSHOT.jar &
