version: 0.0
os: linux
files:
  - source: ./hello-sample-0.0.1-SNAPSHOT.jar
    destination: /tmp
  - source: ./stop.sh
    destination: /tmp
  - source: ./start.sh
    destination: /tmp  
hooks:
  ApplicationStop:
    - location: stop.sh
  ApplicationStart:
    - location: start.sh
