version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build started on `date`
      - gradle build
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/hello-sample-0.0.1-SNAPSHOT.jar
    - scripts/stop.sh
    - scripts/start.sh
    - appspec.yml
  discard-paths: yes
